# Generated by Django 6.0.6 on 2026-08-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('position_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='table_administration_service.employee')),
            ],
            options={
                'db_table': 'question_version',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('weight', models.IntegerField()),
                ('questions_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='table_administration_service.questionversion')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='LeaderLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaders', to='table_administration_service.employee')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='table_administration_service.employee')),
            ],
            options={
                'db_table': 'leader_lead',
                'constraints': [models.UniqueConstraint(fields=('leader', 'lead'), name='unique_leader_lead_pk'), models.CheckConstraint(condition=models.Q(('leader', models.F('lead')), _negated=True), name='chk_no_self_lead')],
            },
        ),
    ]
