# Generated by Django 6.0.6 on 2026-08-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table_administration_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
